name: EasyClick Build with Git LFS

on:
  push:
    branches: [ main, master, lightweight ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code with LFS
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'

    - name: Build EasyClick Agent
      run: |
        echo "Starting build..."
        xcodebuild build-for-testing \
          -project tj-easyclick-agent.xcodeproj \
          -scheme WebDriverAgentRunner \
          -sdk iphoneos \
          -configuration Release \
          -derivedDataPath /tmp/derivedDataPath \
          -allowProvisioningUpdates \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

    - name: Package IPA
      run: |
        cd /tmp/derivedDataPath/Build/Products/Release-iphoneos
        mkdir -p Payload
        mv *.app Payload/ || true
        zip -r EasyClick-Agent.ipa Payload
        ls -la *.ipa

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: EasyClick-Agent
        path: /tmp/derivedDataPath/Build/Products/Release-iphoneos/*.ipa
        retention-days: 30
