name: EasyClick Build for TrollStore (Unsigned)

on:
  push:
    branches: [ main, master, lightweight ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code with LFS
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'

    - name: Build EasyClick Agent (Unsigned for TrollStore)
      run: |
        echo "Building unsigned version for TrollStore..."
        xcodebuild build-for-testing \
          -project tj-easyclick-agent.xcodeproj \
          -scheme WebDriverAgentRunner \
          -sdk iphoneos \
          -configuration Release \
          -derivedDataPath /tmp/derivedDataPath \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          PROVISIONING_PROFILE_SPECIFIER="" \
          DEVELOPMENT_TEAM=""

    - name: Create TrollStore Compatible IPA (Fully Unsigned)
      run: |
        cd /tmp/derivedDataPath/Build/Products/Release-iphoneos
        echo "Creating fully unsigned IPA for TrollStore..."
        
        # Find the app bundle
        APP_NAME=\
        echo "Found app: \"
        
        # Remove all signing related files
        find "\" -name "_CodeSignature" -type d -exec rm -rf {} + 2>/dev/null || true
        find "\" -name "*.mobileprovision" -delete 2>/dev/null || true
        find "\" -name "embedded.mobileprovision" -delete 2>/dev/null || true
        
        # Create clean Payload directory
        rm -rf Payload
        mkdir -p Payload
        cp -r "\" Payload/
        
        # Create IPA
        zip -r EasyClick-Agent-Unsigned.ipa Payload
        ls -la *.ipa
        
        # Show app bundle info
        echo "App bundle contents:"
        ls -la "Payload/\/"

    - name: Upload Unsigned IPA
      uses: actions/upload-artifact@v4
      with:
        name: EasyClick-Agent-Unsigned
        path: /tmp/derivedDataPath/Build/Products/Release-iphoneos/*.ipa
        retention-days: 30
