name: EasyClick Build for TrollStore (Fixed)

on:
  push:
    branches: [ main, master, lightweight ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code with LFS
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'

    - name: Build EasyClick Agent
      run: |
        echo "Building EasyClick Agent..."
        xcodebuild build-for-testing \
          -project tj-easyclick-agent.xcodeproj \
          -scheme WebDriverAgentRunner \
          -sdk iphoneos \
          -configuration Release \
          -derivedDataPath /tmp/derivedDataPath \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          PROVISIONING_PROFILE_SPECIFIER="" \
          DEVELOPMENT_TEAM=""

    - name: Create Unsigned IPA for TrollStore  
      run: |
        cd /tmp/derivedDataPath/Build/Products/Release-iphoneos
        echo "Creating unsigned IPA for TrollStore..."
        
        # List all files to debug
        ls -la
        
        # Create Payload directory
        mkdir -p Payload
        
        # Copy all .app bundles to Payload
        for app in *.app; do
          if [ -d "\" ]; then
            echo "Processing app: \"
            
            # Remove signing files from app bundle
            rm -rf "\/_CodeSignature" 2>/dev/null || true
            rm -f "\/*.mobileprovision" 2>/dev/null || true  
            rm -f "\/embedded.mobileprovision" 2>/dev/null || true
            
            # Copy to Payload
            cp -r "\" Payload/
            echo "Copied \ to Payload"
          fi
        done
        
        # Verify Payload contents
        echo "Payload contents:"
        ls -la Payload/
        
        # Create IPA
        zip -r EasyClick-Agent-TrollStore-Fixed.ipa Payload
        ls -la *.ipa
        
        # Show final IPA size
        du -h *.ipa

    - name: Upload TrollStore IPA
      uses: actions/upload-artifact@v4
      with:
        name: EasyClick-Agent-TrollStore-Fixed
        path: /tmp/derivedDataPath/Build/Products/Release-iphoneos/*.ipa
        retention-days: 30
