name: EasyClick Build with Git LFS

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code with LFS
      uses: actions/checkout@v4
      with:
        lfs: true
        
    - name: Git LFS pull
      run: git lfs pull
      
    - name: Verify LFS files
      run: |
        echo "Checking framework files..."
        ls -la *.framework/ || echo "Framework check complete"
        echo "Checking LFS tracked files..."
        git lfs ls-files
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'
    
    - name: Build EasyClick Agent
      run: |
        echo "Starting build..."
        xcodebuild build-for-testing \
          -project tj-easyclick-agent.xcodeproj \
          -scheme WebDriverAgentRunner \
          -sdk iphoneos \
          -configuration Release \
          -derivedDataPath /tmp/derivedDataPath \
          -allowProvisioningUpdates \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
    
    - name: Package IPA
      run: |
        cd /tmp/derivedDataPath/Build/Products/Release-iphoneos
        echo "Cleaning unwanted apps..."
        rm -rf IntegrationApp.app || true
        echo "Creating Payload directory..."
        mkdir -p Payload
        echo "Moving app to Payload..."
        mv *.app Payload/ || true
        echo "Creating IPA..."
        zip -r EasyClick-Agent-LFS.ipa Payload
        echo "IPA file info:"
        ls -la EasyClick-Agent-LFS.ipa
    
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: EasyClick-Agent-LFS
        path: /tmp/derivedDataPath/Build/Products/Release-iphoneos/EasyClick-Agent-LFS.ipa
        retention-days: 30
        
    - name: Build success
      run: |
        echo "Build successful!"
        echo "IPA file generated for iOS installation"
        echo "This is EasyClick specialized version with complete iosauto framework"
