name: WebDriverAgent TrollStore Build

on:
  workflow_dispatch:
  push:
    branches: [ main, wda-trollstore ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout WebDriverAgent 9.14.6
      uses: actions/checkout@v4
      with:
        path: wda
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'
    
    - name: Copy WebDriverAgent Source
      run: |
        mkdir -p build
        cp -r "untitled/src/js/WebDriverAgent-9.14.6/WebDriverAgent-9.14.6" "build/WebDriverAgent"
        ls -la build/WebDriverAgent/
        
    - name: Install Node.js Dependencies
      run: |
        cd build/WebDriverAgent
        npm install
        
    - name: Build WebDriverAgent for iOS Device
      run: |
        cd build/WebDriverAgent
        export TARGET=runner
        export SDK=device
        export DERIVED_DATA_PATH="$(pwd)/wdaBuild"
        export IPHONE_MODEL="iPhone 15"
        export IOS_VERSION="17.5"
        export DEST=generic
        export ACTION=build
        export CODE_SIGN=no
        
        echo "Building WebDriverAgent with settings:"
        echo "TARGET: $TARGET"
        echo "SDK: $SDK"
        echo "DEST: $DEST"
        
        # Build using the official script
        bash Scripts/build.sh
        
    - name: Locate Built App
      run: |
        cd build/WebDriverAgent
        echo "Searching for .app files..."
        find . -name "*.app" -type d | head -20
        
        # Find the runner app
        RUNNER_APP=$(find . -name "WebDriverAgentRunner-Runner.app" -type d | head -1)
        if [ -z "$RUNNER_APP" ]; then
          echo "WebDriverAgentRunner-Runner.app not found, trying alternative names..."
          RUNNER_APP=$(find . -name "*Runner*.app" -type d | head -1)
        fi
        
        if [ -n "$RUNNER_APP" ]; then
          echo "Found app at: $RUNNER_APP"
          echo "APP_PATH=$RUNNER_APP" >> $GITHUB_ENV
          
          # Show app contents
          echo "App contents:"
          ls -la "$RUNNER_APP"
        else
          echo "No .app file found!"
          exit 1
        fi
        
    - name: Create TrollStore-Compatible IPA
      run: |
        cd build/WebDriverAgent
        
        echo "Creating IPA for TrollStore..."
        
        # Create proper IPA structure
        mkdir -p IPA_Build/Payload
        
        # Copy the app bundle (using mv like original buildipa.sh)
        echo "Moving app from $APP_PATH to Payload/"
        mv "$APP_PATH" IPA_Build/Payload/
        
        # Verify the structure
        echo "IPA structure:"
        find IPA_Build -type f | head -20
        
        # Create TrollStore entitlements
        cat > IPA_Build/Payload/*.app/entitlements.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>get-task-allow</key>
            <true/>
            <key>com.apple.private.dtrace.allow</key>
            <true/>
            <key>com.apple.private.security.no-container</key>
            <true/>
            <key>com.apple.private.skip-library-validation</key>
            <true/>
        </dict>
        </plist>
        EOF
        
        # Remove any existing signatures for clean install
        find IPA_Build/Payload/*.app -name "_CodeSignature" -type d -exec rm -rf {} + 2>/dev/null || true
        find IPA_Build/Payload/*.app -name "*.mobileprovision" -delete 2>/dev/null || true
        rm -f IPA_Build/Payload/*.app/embedded.mobileprovision 2>/dev/null || true
        
        # Create the IPA
        cd IPA_Build
        zip -r "../WebDriverAgent-TrollStore.ipa" Payload/
        cd ..
        
        # Verify IPA creation
        if [ -f "WebDriverAgent-TrollStore.ipa" ]; then
          echo "✅ IPA created successfully!"
          ls -lh WebDriverAgent-TrollStore.ipa
          
          # Show IPA contents
          echo "IPA contents:"
          unzip -l WebDriverAgent-TrollStore.ipa | head -20
        else
          echo "❌ Failed to create IPA!"
          exit 1
        fi
        
    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WebDriverAgent-TrollStore
        path: build/WebDriverAgent/WebDriverAgent-TrollStore.ipa
        
    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/wda-trollstore'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: wda-v${{ github.run_number }}
        name: WebDriverAgent TrollStore v${{ github.run_number }}
        body: |
          WebDriverAgent 9.14.6 - TrollStore优化版本
          
          **安装说明:**
          1. 下载 WebDriverAgent-TrollStore.ipa
          2. 通过TrollStore安装
          3. 启动应用并开始使用
          
          **构建信息:**
          - WebDriverAgent版本: 9.14.6
          - Xcode版本: 15.4
          - 针对TrollStore优化
          - 移除代码签名冲突
        files: build/WebDriverAgent/WebDriverAgent-TrollStore.ipa
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 